version : '3.7'

services:
  server:
    platform: linux/amd64
    build:
      context: ./
      dockerfile : dockerfile
    image: ${DOCKER_USER_ID}/jenkins-test
    volumes:
      - ./:/app
    ports : 
      -  80:80
