version : '3.7'

services:
  server:
    platform: linux/amd64
    build:
      context: ./
      dockerfile : dockerfile
    image: jenkins_tests
    volumes:
      - ./:/app
    ports : 
      -  80:80
